//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PojectGANkurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctorsappoin
    {
        public int iddoctorappoint { get; set; }
        public int idregistr { get; set; }
        public System.DateTime Dateappoint { get; set; }
        public int idDisease { get; set; }
        public int idMedicament { get; set; }
        public string Comment { get; set; }
        public int Medicamentquantity { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Medicament Medicament { get; set; }
        public virtual Registr Registr { get; set; }
    }
}
