//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PojectGANkurs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class registrGANEntities : DbContext
    {
        public registrGANEntities()
            : base("name=registrGANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cabin> cabin { get; set; }
        public virtual DbSet<Disease> Disease { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Doctorsappoin> Doctorsappoin { get; set; }
        public virtual DbSet<Medicament> Medicament { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Rasp> Rasp { get; set; }
        public virtual DbSet<Registr> Registr { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Typepay> Typepay { get; set; }
        public virtual DbSet<UserRegistr> UserRegistr { get; set; }
    }
}
