//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PojectGANkurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registr()
        {
            this.Doctorsappoin = new HashSet<Doctorsappoin>();
        }
    
        public int idRegistr { get; set; }
        public int idPatient { get; set; }
        public int iduserRegistr { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public int idTypepay { get; set; }
        public int idrasp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctorsappoin> Doctorsappoin { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual Rasp Rasp { get; set; }
        public virtual Typepay Typepay { get; set; }
        public virtual UserRegistr UserRegistr { get; set; }
    }
}
